check:
  - thoth-build
build:
  base-image: "quay.io/modh/s2i-python-anaconda-base:latest"
  build-stratergy: Source
  registry: quay.io
  registry-org: modh
  registry-project: s2i-minimal-notebook-anaconda
  registry-secret: modh-pusher-secret
